### ISSUE TITLE
OpenCWB Integration Failed to connect

### ISSUE THREAD

**Issue by hopperjef** [tsunglung/OpenCWB#2]
I have my API Key from opendata.cwb.gov.tw and I added OpenCWB to HACS with the custom repo but when I try to add the integration I get the error "Failed to connect." Any suggestions for other things I can try to make this work?
![OpenCWB](https://user-images.githubusercontent.com/79919919/151123557-2fdab1ce-ffac-4ab9-87ea-a11185c65650.jpg)

**Comment by tsunglung** [comment]
what is your ha installed?
hassos or hass core?

**Comment by hopperjef** [comment]
I'm not sure what the difference is, core I think?
Version | core-2021.12.9
Installation Type | Home Assistant OS
Running on a Raspberry Pi 4b

**Comment by Candyfox233** [comment]
我有一樣的問題

版本 | core-2022.6.7
安裝類別 | Home Assistant OS

**Comment by umas2019** [comment]
我也有一樣的問題

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

**Comment by shaoming0905** [comment]
請問一下鄉鎮名稱那個是要輸入甚麼，我怎樣打都是無效鄉鎮名稱，謝謝
