### ISSUE TITLE
Invalid config 

### ISSUE THREAD

**Issue by sbeagle25** [tsunglung/OpenCWB#3]
Recently I got an error from OpenCWB. I try to reinstall several times but still the same.

`Unable to prepare setup for platform opencwb.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform opencwb.weather: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).`

core-2021.11.3
Home Assistant OS

**Comment by tsunglung** [comment]
Try upgrade hass core
