### ISSUE TITLE
Ambiguous entity names

### ISSUE THREAD

**Issue by Teeeeemo** [tsunglung/OpenCWB#6]
Hi, I realized that the entity names are ambiguous (opencwb_1, opencwb_2, etc). Is it possible to keep the entity name from the CWB?
![image](https://user-images.githubusercontent.com/12287936/192152888-b0448939-842d-462d-bd8a-f1df2832eaea.png)

**Comment by Teeeeemo** [comment]
嗨，我意識到實體名稱不明確（opencwb_1、opencwb_2 等）。 是否可以保留 CWB 中的實體名稱？

**Comment by julian0703** [comment]
entity_id | unique_id
-- | --
sensor.opencwb | weather
sensor.opencwb_2 | dew_point
sensor.opencwb_3 | temperature
sensor.opencwb_4 | feels_like_temperature
sensor.opencwb_5 | wind_speed
sensor.opencwb_6 | wind_bearing
sensor.opencwb_7 | humidity
sensor.opencwb_8 | clouds
sensor.opencwb_9 | uv_index
sensor.opencwb_10 | condition
sensor.opencwb_11 | weather_code
sensor.opencwb_forecast | forecast-condition
sensor.opencwb_forecast_2 | forecast-precipitation
sensor.opencwb_forecast_3 | forecast-precipitation_probability
sensor.opencwb_forecast_4 | forecast-temperature
sensor.opencwb_forecast_5 | forecast-datetime
sensor.opencwb_forecast_6 | forecast-wind_bearing
sensor.opencwb_forecast_7 | forecast-wind_speed
weather.opencwb | onecall_hourly

**Comment by tsunglung** [comment]
Fixed, please remove and add again.
